export enum Permission {
  CREAR_DOCUMENTO = 'GESTIONDOCUMENTAL_CREAR_DOCUMENTO_DOC', //
  OBTENER_DOCUMENTOS = 'GESTIONDOCUMENTAL_OBTENER_DOCUMENTO_DOC', //
  EDITAR_DOCUMENTO = 'GESTIONDOCUMENTAL_EDITAR_DOCUMENTO_DOC', //
  ELIMINAR_DOCUMENTO = 'GESTIONDOCUMENTAL_ELIMINAR_DOCUMENTO_DOC', //
  REACTIVAR_DOCUMENTO = 'GESTIONDOCUMENTAL_REACTIVAR_DOCUMENTO_DOC', //
  VER_DOCUMENTOS_TODOS = 'GESTIONDOCUMENTAL_VER_DOCUMENTOS_TODOS',
  VER_DOCUMENTOS_ACTIVADOS = 'GESTIONDOCUMENTAL_VER_DOCUMENTOS_ACTIVADOS', //
  VER_DOCUMENTOS_INACTIVOS = 'GESTIONDOCUMENTAL_VER_DOCUMENTOS_INACTIVOS', //
  VER_BITACORA = 'GESTIONDOCUMENTAL_VER_BITACORA', //

  //ver si se puede poner
  REVISAR_DOCUMENTO = 'GESTIONDOCUMENTAL_REVISAR_DOCUMENTO',
  MARCAR_DOCUMENTO = 'GESTIONDOCUMENTAL_MARCAR_DOCUMENTO',
  COMENTAR_DOCUMENTO = 'GESTIONDOCUMENTAL_COMENTAR_DOCUMENTO',
  ADJUNTAR_HITO_DOCUMENTO = 'GESTIONDOCUMENTAL_ADJUNTAR_HITO_DOCUMENTO',

  ENVIAR_DOCUMENTO = 'GESTIONDOCUMENTAL_ENVIAR_DOCUMENTO', //
  DERIVAR_DOCUMENTO = 'GESTIONDOCUMENTAL_DERIVAR_DOCUMENTO', //
  OBSERVAR_DOCUMENTO = 'GESTIONDOCUMENTAL_OBSERVAR_DOCUMENTO', //

  //nuevo nuevo
  VER_SEGUIMIENTO = 'GESTIONDOCUMENTAL_VER_SEGUIMIENTO', //

  CREAR_TIPO_DOCUMENTACION = 'GESTIONDOCUMENTAL_CREAR_TIPO_DOCUMENTACION_DOC',
  OBTENER_TIPOS_DOCUMENTACION = 'GESTIONDOCUMENTAL_OBTENER_TIPOS_DOCUMENTACION_DOC',
  EDITAR_TIPOS_DOCUMENTACION = 'GESTIONDOCUMENTAL_EDITAR_TIPOS_DOCUMENTACION_DOC',
  ELIMINAR_TIPOS_DOCUMENTACION = 'GESTIONDOCUMENTAL_ELIMINAR_TIPOS_DOCUMENTACION_DOC',
  REACTIVAR_TIPOS_DOCUMENTACION = 'GESTIONDOCUMENTAL_REACTIVAR_TIPOS_DOCUMENTACION_DOC',

  CREAR_WORKLFOW = 'GESTIONDOCUMENTAL_CREAR_WORKFLOW_DOC', //
  OBTENER_WORKFLOWS = 'GESTIONDOCUMENTAL_OBTENER_WORKFLOW_DOC', //
  OBTENER_WORKFLOW_ONE = 'GESTIONDOCUMENTAL_OBTENER_WORKFLOW_ONE_DOC', //
  EDITAR_WORKFLOW = 'EDITAR_WORKFLOW_DOC', //
  ELIMINAR_WORKFLOW = 'GESTIONDOCUMENTAL_ELIMINAR_WORKFLOW_DOC', //
  REACTIVAR_WORKFLOW = 'GESTIONDOCUMENTAL_REACTIVAR_WORKFLOW_DOC', //

  // CREAR_STEP = 'GESTIONDOCUMENTAL_CREAR_STEP_DOC',
  // OBTENER = 'OBTENER_STEP_DOC',
  // EDITAR_STEP = 'GESTIONDOCUMENTAL_EDITAR_STEP_DOC',
  // ELIMINAR_STEP = 'GESTIONDOCUMENTAL_ELIMINAR_STEP_DOC',
  // REACTIVAR_STEP = 'GESTIONDOCUMENTAL_REACTIVAR_STEP_DOC',

  // CREAR_ROL = 'CREAR_ROL_DOC',
  // OTENER_ROL = 'OBTENER_ROL_DOC',
  // EDITAR_ROL = 'EDITAR_ROL_DOC',
  // ELIMINAR_ROL = 'ELIMINAR_ROL_DOC',

  // CREAR_PERMISO = 'CREAR_PERMISO_DOC',
  // OBTENER_PERMISO = 'OBTENER_PERMISO_DOC',
  // EDITAR_PERMISO = 'EDITAR_PERMISO_DOC',
  // ELIMINAR_PERMISO = 'ELIMINAR_PERMISO_DOC',

  GENERAR_CREDENCIALES_FIRMA_DIGITAL = 'GESTIONDOCUMENTAL_GENERAR_CREDENCIALES_FIRMA_DIGITAL', //
  FIRMAR_DOCUMENTO = 'GESTIONDOCUMENTAL_FIRMAR_DOCUMENTO', //
  VER_USUARIOS_CREDENCIALES = 'GESTIONDOCUMENTAL_VER_USUARIOS_CREDENCIALES', //
  VER_DOCUMENTOS_CON_FIRMA = 'GESTIONDOCUMENTAL_VER_DOCUMENTOS_CON_FIRMA', //
  RECUPERAR_PIN = 'GESTIONDOCUMENTAL_RECUPERAR_PIN', //
  VER_DOCUMENTO_CON_FIRMA_ID = 'GESTIONDOCUMENTAL_VER_DOCUMENTO_CON_FIRMA_ID', //
  ELIMINAR_FIRMA_DOCUMENTO = 'GESTIONDOCUMENTAL_ELIMINAR_FIRMA_DOCUMENTO', //

  // CREAR_HOJA_DE_RUTA = 'GESTIONDOCUMENTAL_CREAR_HOJA_DE_RUTA',
  // ASIGNAR_HOJA_RUTA_DOCUMENTO = 'GESTIONDOCUMENTAL_ASIGNAR_HOJA_RUTA_DOCUMENTO',

  USUARIO_LOGEADO = 'GESTIONDOCUMENTAL_USUARIO_LOGEADO', //
  USER = 'USER',
  ADMIN = 'ADMIN',
  SUPERADMIN = 'SUPERADMIN',
}

/*
export enum Permission {
  CREAR_DOCUMENTO = 'GESTIONDOCUMENTAL_CREAR_DOCUMENTO_DOC',
  OBTENER_DOCUMENTOS = 'OBTENER_DOCUMENTO_DOC',
  EDITAR_DOCUMENTO = 'EDITAR_DOCUMENTO_DOC',
  ELIMINAR_DOCUMENTO = 'ELIMINAR_DOCUMENTO_DOC',
  REACTIVAR_DOCUMENTO = 'REACTIVAR_DOCUMENTO_DOC',

  CREAR_TIPO_DOCUMENTACION = 'CREAR_TIPO_DOCUMENTACION_DOC',
  OBTENER_TIPOS_DOCUMENTACION = 'OBTENER_TIPOS_DOCUMENTACION_DOC',
  EDITAR_TIPOS_DOCUMENTACION = 'EDITAR_TIPOS_DOCUMENTACION_DOC',
  ELIMINAR_TIPOS_DOCUMENTACION = 'ELIMINAR_TIPOS_DOCUMENTACION_DOC',
  REACTIVAR_TIPOS_DOCUMENTACION = 'REACTIVAR_TIPOS_DOCUMENTACION_DOC',

  CREAR_WORKLFOW = 'CREAR_WORKFLOW_DOC',
  OBTENER_WORKFLOWS = 'OBTENER_WORKFLOWS_DOC',
  OBTENER_WORKFLOW_ONE = 'OBTENER_WORKFLOW_ONE_DOC',
  EDITAR_WORKFLOW = 'EDITAR_WORKFLOW_DOC',
  ELIMINAR_WORKFLOW = 'ELIMINAR_WORKLFOW_DOC',
  REACTIVAR_WORKFLOW = 'REACTIVAR_WORKFLOW_DOC',

  CREAR_STEP = 'CREAR_STEP_DOC',
  OBTENER = 'OBTENER_STEP_DOC',
  EDITAR_STEP = 'EDITAR_STEP_DOC',
  ELIMINAR_STEP = 'ELIMINAR_STEP_DOC',
  REACTIVAR_STEP = 'REACTIVAR_STEP_DOC',

  CREAR_ROL = 'CREAR_ROL_DOC',
  OTENER_ROL = 'OBTENER_ROL_DOC',
  EDITAR_ROL = 'EDITAR_ROL_DOC',
  ELIMINAR_ROL = 'ELIMINAR_ROL_DOC',

  CREAR_PERMISO = 'CREAR_PERMISO_DOC',
  OBTENER_PERMISO = 'OBTENER_PERMISO_DOC',
  EDITAR_PERMISO = 'EDITAR_PERMISO_DOC',
  ELIMINAR_PERMISO = 'ELIMINAR_PERMISO_DOC',

  USER = 'USER',
  ADMIN = 'ADMIN',
  SUPERADMIN = 'SUPERADMIN',
}

*/
