version: '3.4'

services:
  my-nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8085:8085
    depends_on:
      - mongo
  
  mongo:
    container_name: mongo_v2
    image: 'mongo:4.4'
    environment:
      - MONGO_DATA_DIR=/data/db
    ports:
      - '27018:27017'
    volumes:
      - mongo:/data/db

volumes:
  mongo:

# SOLO PARA PRUEBAS
# version: '3.4'

# services:
#   mongo:
#     container_name: mongo_v2
#     image: 'mongo:4.4'
#     environment:
#       - MONGO_DATA_DIR=/data/db
#     ports:
#       - '27017:27017'
#     volumes:
#       - mongo:/data/db

# volumes:
#   mongo:







# version: '3'
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 8085:8085
#     environment:
#       - NODE_ENV=development
#     depends_on:
#       - mongo
#   mongo:
#     image: mongo
#     volumes:
#       - ./data:/data/db


