version: '3.4'

services:
  mongo:
    container_name: mongo
    image: 'mongo:6.0.6'
    environment:
      - MONGO_DATA_DIR=/data/db
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db

volumes:
  mongo: