version: '3'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:3000'
    depends_on:
      - database
  database:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase


    